version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo BUILD_STARTED
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo BUILD_FINISHED
artifacts:
  files:
    - target/onex-rest-demo-0.0.1.jar